apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: loki-grafana
data:
  fluent.conf: |-
    @include pods-fluent.conf
    @include gcs-loki-fluent.conf
  pods-fluent.conf: |-
    <label @FLUENT_LOG>
        <match fluent.*>
            @type null
        </match>
    </label>
    <source>
      @type tail
      read_from_head true
      tag kubernetes.*
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      exclude_path /var/log/containers/fluentd*.log
      path_key filename_prod
      <parse>
        @type json
        time_type string
      </parse>
    </source>
    #<source>
    #   @type tail
    #   read_from_head true
    #   tag service.*
    #   path /var/log/containers/service-*.log
    #   pos_file /var/log/service-containers.log.pos
    #   path_key service_prod
    #   <parse>
    #      @type json
    #      time_type string
    #   </parse>
    # </source>
    #<filter service.**>
    #  @type parser
    #  key_name Object
    #  reserve_data true
    #  remove_key_name_field true
    #  <parse>
    #    @type multi_format
    #    <pattern>
    #       format json
    #    </pattern>
    #    <pattern>
    #       format none
    #    </pattern>
    #  </parse>
    #</filter>
    #########OPTIONAL################

    ######## IF you un-comment this you will get kuberenetes_meta data metrics in your logs#########
    # <filter kubernetes.**>
    #   @type kubernetes_metadata
    #   @id filter_kube_metadata
    #   kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
    #   verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
    #   ca_file "#{ENV['KUBERNETES_CA_FILE']}"
    #   skip_labels "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_LABELS'] || 'false'}"
    #   skip_container_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_CONTAINER_METADATA'] || 'false'}"
    #   skip_master_url "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_MASTER_URL'] || 'false'}"
    #   skip_namespace_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_NAMESPACE_METADATA'] || 'false'}"
    #</filter>
  gcs-loki-fluent.conf: |-
    <match **>
      @type copy
      <store>
        @type gcs

        project "#{ENV['GCS_BUCKET_PROJECT']}"
        keyfile "#{ENV['GCP_CRED']}"
        bucket "#{ENV['GCS_BUCKET_NAME']}"
        object_key_format %{path}%{time_slice}_%{index}.%{file_extension}
        path prod_logs/${tag}/%Y/%m/%d/

         <buffer tag,time>
            @type file
            path /var/log/fluent/gcs
            timekey 1h
            timekey_wait 10min
            timekey_use_utc true
            flush_at_shutdown true
         </buffer>
         <format>
            @type json
         </format>
      </store>
      <store>
        @type loki
        #######------Your Remote loki-----#######
        url "http://10.451.1.0:3100"
        extra_labels {"cluster":"prod"}
        <label>
          filename_prod
        </label>
        extract_kubernetes_labels true
        <buffer time,tag>
          flush_at_shutdown true
          flush_mode interval
          flush_interval 10
          timekey 20
          timekey_wait 60
          chunk_limit_size 60MB
        </buffer>
      </store>
    </match>
